"""Rate-limited, concurrency-capped async HTTP client.

All network traffic generated by the toolkit flows through HttpClient so that a
single rate limit and concurrency cap apply across every phase, keeping the
assessment polite and avoiding accidental denial-of-service.
"""

from __future__ import annotations

import asyncio
import time

import httpx

DEFAULT_UA = (
    "Sentinel/0.1 (+authorized-security-assessment) "
    "Mozilla/5.0 (compatible)"
)


class RateLimiter:
    """Token-free leaky-bucket: enforces a minimum gap between requests."""

    def __init__(self, rate_per_sec: float) -> None:
        self._min_interval = 1.0 / rate_per_sec if rate_per_sec > 0 else 0.0
        self._lock = asyncio.Lock()
        self._next_allowed = 0.0

    async def wait(self) -> None:
        if self._min_interval <= 0:
            return
        async with self._lock:
            now = time.monotonic()
            wait_for = self._next_allowed - now
            if wait_for > 0:
                await asyncio.sleep(wait_for)
            self._next_allowed = max(now, self._next_allowed) + self._min_interval


class HttpClient:
    """Thin wrapper over httpx.AsyncClient with global throttling."""

    def __init__(
        self,
        rate: float = 10.0,
        concurrency: int = 10,
        timeout: float = 15.0,
        user_agent: str = DEFAULT_UA,
        verify_tls: bool = True,
    ) -> None:
        self._limiter = RateLimiter(rate)
        self._sem = asyncio.Semaphore(concurrency)
        self._client = httpx.AsyncClient(
            timeout=timeout,
            verify=verify_tls,
            follow_redirects=False,
            headers={"User-Agent": user_agent},
            limits=httpx.Limits(max_connections=concurrency * 2),
        )
        self.request_count = 0
        self.error_count = 0

    async def request(
        self, method: str, url: str, **kwargs
    ) -> httpx.Response | None:
        """Perform a request; return the response, or None on any failure.

        Scanners routinely send payloads that produce malformed URLs or
        redirect targets; every such failure must degrade to None, never
        crash the assessment.
        """
        async with self._sem:
            await self._limiter.wait()
            self.request_count += 1
            try:
                return await self._client.request(method, url, **kwargs)
            except (httpx.HTTPError, httpx.InvalidURL, ValueError,
                    UnicodeError, OSError):
                self.error_count += 1
                return None

    async def get(self, url: str, **kwargs) -> httpx.Response | None:
        return await self.request("GET", url, **kwargs)

    async def head(self, url: str, **kwargs) -> httpx.Response | None:
        return await self.request("HEAD", url, **kwargs)

    async def post(self, url: str, **kwargs) -> httpx.Response | None:
        return await self.request("POST", url, **kwargs)

    async def aclose(self) -> None:
        await self._client.aclose()
