"""Generates a standalone Python script that reproduces a scan's findings.

The generated `reproduce.py` is self-contained (standard library only) and
non-destructive: each reproduce_* function re-issues the request(s) that prove
ONE finding, then stops. It is the automatable form of a hand-written PoC.
"""

from __future__ import annotations

from sentinel.context import Context

# Verify types that have a reproduction recipe, and a friendly label for each.
_LABELS = {
    "sqli": "SQL injection",
    "xss": "Reflected XSS",
    "open_redirect": "Open redirect",
    "exposed_file": "Exposed file",
    "unauth_access": "Broken access control",
    "payload_exec": "Server-side payload execution",
}

_HEADER = '''#!/usr/bin/env python3
"""
Reproduction script auto-generated by Sentinel.

  Target    : {target}
  Generated : {generated}
  Findings  : {n} reproducible of {total} total in this scan

Each reproduce_* function below re-issues the request(s) that demonstrate ONE
finding. Every check is non-destructive -- it proves the issue exists and then
stops. Nothing is exploited, dumped, or modified.

  AUTHORIZATION: run this ONLY against systems you are authorized to test.

Usage:  python3 reproduce.py
"""

import sys
import urllib.error
import urllib.parse
import urllib.request

TARGET = {target!r}
TIMEOUT = 15
UA = "sentinel-repro"


class _NoRedirect(urllib.request.HTTPRedirectHandler):
    """Opener handler that refuses to follow redirects (so we can read them)."""

    def redirect_request(self, *args, **kwargs):
        return None


_no_redirect = urllib.request.build_opener(_NoRedirect)
_SQL_ERRORS = ("sql syntax", "mysqli", "ora-", "unclosed quotation",
               "sqlite", "postgresql", "odbc", "syntax error")


def with_param(url, name, value):
    """Return url with query parameter `name` set to `value`."""
    parts = urllib.parse.urlparse(url)
    query = dict(urllib.parse.parse_qsl(parts.query, keep_blank_values=True))
    query[name] = value
    return urllib.parse.urlunparse(
        parts._replace(query=urllib.parse.urlencode(query)))


def fetch(url):
    """GET url (following redirects); return the body, or '' on failure."""
    req = urllib.request.Request(url, headers={{"User-Agent": UA}})
    try:
        with urllib.request.urlopen(req, timeout=TIMEOUT) as resp:
            return resp.read().decode("utf-8", errors="replace")
    except urllib.error.HTTPError as exc:
        return exc.read().decode("utf-8", errors="replace")
    except Exception as exc:  # noqa: BLE001
        print("  !! request failed: " + repr(exc))
        return ""


def fetch_status_location(url):
    """GET url WITHOUT following redirects; return (status, Location header)."""
    req = urllib.request.Request(url, headers={{"User-Agent": UA}})
    try:
        with _no_redirect.open(req, timeout=TIMEOUT) as resp:
            return resp.status, resp.headers.get("Location", "")
    except urllib.error.HTTPError as exc:
        return exc.code, exc.headers.get("Location", "")
    except Exception as exc:  # noqa: BLE001
        print("  !! request failed: " + repr(exc))
        return 0, ""


def has_sql_error(body):
    low = body.lower()
    return any(sig in low for sig in _SQL_ERRORS)
'''

_T_SQLI = '''

def {name}():
    print({banner!r})
    url, param, base = {url!r}, {param!r}, {value!r}
    # An unbalanced quote breaks the SQL statement; a balanced one does not.
    unbalanced = fetch(with_param(url, param, base + "'"))
    balanced = fetch(with_param(url, param, base + "' AND '1'='1"))
    if has_sql_error(unbalanced) and not has_sql_error(balanced):
        print("  CONFIRMED: the unbalanced quote produced a SQL error while "
              "the balanced payload did not -> the parameter is injected into "
              "a SQL statement. (No data was read.)")
        return True
    print("  not reproduced: no SQL-error differential observed this run.")
    return False
'''

_T_XSS = '''

def {name}():
    print({banner!r})
    # A script-free tag: if it comes back un-encoded, input reaches HTML.
    probe = 'sentinelpoc"><svg data-sentinel-poc></svg>'
    body = fetch(with_param({url!r}, {param!r}, probe))
    if "<svg data-sentinel-poc></svg>" in body:
        print("  CONFIRMED: the HTML tag was reflected unescaped -> input "
              "reaches an executable HTML context. (No JavaScript was run.)")
        return True
    print("  not reproduced: the tag was encoded or absent.")
    return False
'''

_T_REDIRECT = '''

def {name}():
    print({banner!r})
    status, location = fetch_status_location(
        with_param({url!r}, {param!r}, "https://sentinel-poc.example/"))
    if status in (301, 302, 303, 307, 308) and "sentinel-poc.example" in location:
        print("  CONFIRMED: HTTP " + str(status) + " redirect to the "
              "attacker-controlled host -> Location: " + location)
        return True
    print("  not reproduced: no off-site redirect was issued.")
    return False
'''

_T_EXPOSED = '''

def {name}():
    print({banner!r})
    body = fetch({url!r})
    if body.strip():
        print("  CONFIRMED: the file is publicly retrievable (" +
              str(len(body)) + " bytes). Its contents are NOT printed here.")
        return True
    print("  not reproduced: the file was not retrievable.")
    return False
'''

_T_UNAUTH = '''

def {name}():
    print({banner!r})
    # Request with NO credentials -- our client sends no cookies.
    body = fetch({url!r}).lower()
    auth_markers = ("logout", "log out", "sign out")
    admin_markers = ("dashboard", "admin panel", "manage users",
                     "administration", "settings")
    if any(m in body for m in auth_markers) and \\
            any(m in body for m in admin_markers):
        print("  CONFIRMED: an authenticated admin area was reached with NO "
              "credentials -> broken access control. Reproduction STOPS here "
              "-- no action is taken inside the area.")
        return True
    print("  not reproduced: no authenticated-area markers found.")
    return False
'''

_T_EXEC = '''

def {name}():
    print({banner!r})
    payload, proof = {payload!r}, {proof!r}
    body = fetch(with_param({url!r}, {param!r}, payload))
    sent_literally = payload in body
    evaluated = bool(proof) and (proof in body) and not sent_literally
    if evaluated:
        print("  CONFIRMED: sent " + repr(payload) + ", the server returned " +
              repr(proof) + " -> it evaluated input you supplied in the URL.")
        return True
    if sent_literally:
        print("  not reproduced: payload echoed literally (safe behaviour).")
    else:
        print("  not reproduced: inconclusive this run.")
    return False
'''

_TEMPLATES = {
    "sqli": _T_SQLI,
    "xss": _T_XSS,
    "open_redirect": _T_REDIRECT,
    "exposed_file": _T_EXPOSED,
    "unauth_access": _T_UNAUTH,
    "payload_exec": _T_EXEC,
}

_MAIN = '''

# Every reproducer for this scan, in severity order.
REPRODUCERS = [
{calls}]


def main():
    print("=" * 72)
    print("  Sentinel reproduction script")
    print("  target: " + TARGET)
    print("=" * 72)
    if not REPRODUCERS:
        print("\\n  No reproducible findings were recorded in this scan.")
        return 0
    confirmed = 0
    for reproducer in REPRODUCERS:
        print()
        try:
            if reproducer():
                confirmed += 1
        except Exception as exc:  # noqa: BLE001
            print("  !! reproduction error: " + repr(exc))
    print()
    print("=" * 72)
    print("  VERDICT: " + str(confirmed) + " of " + str(len(REPRODUCERS)) +
          " finding(s) reproduced.")
    print("=" * 72)
    return 1 if confirmed else 0


if __name__ == "__main__":
    sys.exit(main())
'''


def generate(ctx: Context, generated_iso: str) -> str:
    """Build the full text of a reproduce.py script for this scan."""
    blocks: list[str] = []
    names: list[str] = []

    # Severity order keeps the most serious reproductions first.
    findings = sorted(ctx.findings, key=lambda f: f.rank)
    for finding in findings:
        template = _TEMPLATES.get(finding.verify_type)
        if template is None:
            continue
        data = finding.verify_data
        if "url" not in data:
            continue
        idx = len(names) + 1
        name = f"reproduce_{idx}_{finding.verify_type}"
        names.append(name)
        label = _LABELS.get(finding.verify_type, finding.verify_type)
        banner = f"[{idx}] {label} -- {finding.target}"
        blocks.append(template.format(
            name=name,
            banner=banner,
            url=data.get("url", ""),
            param=data.get("param", ""),
            value=str(data.get("value", "1")),
            payload=data.get("payload", ""),
            proof=data.get("proof", ""),
        ))

    header = _HEADER.format(
        target=ctx.scope.root_url,
        generated=generated_iso,
        n=len(names),
        total=len(ctx.findings),
    )
    calls = "".join(f"    {name},\n" for name in names)
    return header + "".join(blocks) + _MAIN.format(calls=calls)
